
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
interface MyInterface {

    function myPublicFunction(uint value) external;
    //function myPrivateFunction(uint value) external;
    function myExternalFunction(uint value) external;
    //function myInternalFunction(uint value) external;

}
